// <auto-generated />
using System;
using FirstCloudProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FirstCloudProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221022214027_addMemCache")]
    partial class addMemCache
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("FirstCloudProject.Models.Image", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("FirstCloudProject.Models.MemoryCacheSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Hit")
                        .HasColumnType("int");

                    b.Property<int>("Miss")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRequests")
                        .HasColumnType("int");

                    b.Property<int>("TotalItemsNum")
                        .HasColumnType("int");

                    b.Property<long>("TotalSizeOfItems")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("MemoryCacheSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
